services:
  db:
    platform: linux/amd64
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pertakecast
    volumes:
      - postgres-data:/var/lib/postgres
    ports:
      - 5432:5432
volumes:
  postgres-data:
